django_forum/urls.py
"""
    _summary_
"""
from django import urls

from . import views as forum_views
from . import views_forum_post as forum_post_views

app_name = "django_forum"

postview_patterns = [
    urls.path("posts/", forum_post_views.PostList.as_view(), name="post_list_view"),
    urls.path(
        "post/<int:pk>/<slug:slug>/",
        forum_post_views.PostView.as_view(),
        name="post_view",
    ),
    urls.path(
        "create_post/", forum_post_views.PostCreate.as_view(), name="post_create_view"
    ),
    urls.path(
        "update_post/<int:pk>/<slug:slug>/",
        forum_post_views.PostUpdate.as_view(),
        name="post_update",
    ),
    urls.path(
        "delete_post/<int:pk>/<slug:slug>/",
        forum_post_views.PostDelete.as_view(),
        name="post_delete",
    ),
    urls.path(
        "report_post/<int:pk>/<slug:slug>/",
        forum_post_views.ReportPost.as_view(),
        name="post_report",
    ),
    urls.path(
        "create_comment/<int:pk>/<slug:slug>/",
        forum_post_views.CreateComment.as_view(),
        name="comment_create",
    ),
    urls.path(
        "delete_comment/<int:pk>/<slug:slug>/",
        forum_post_views.DeleteComment.as_view(),
        name="comment_delete",
    ),
    urls.path(
        "update_comment/<int:pk>/<slug:slug>/",
        forum_post_views.UpdateComment.as_view(),
        name="comment_update",
    ),
    urls.path(
        "report_comment/<int:pk>/<slug:slug>/",
        forum_post_views.ReportComment.as_view(),
        name="comment_report",
    ),
    urls.path("subscribe/", forum_post_views.subscribe, name="subscribe"),
]

urlpatterns = [
    urls.path(
        "profile/", forum_views.ForumProfile.as_view(), name="profile_update_view"
    ),
    urls.path(
        "update_avatar/", forum_views.UpdateAvatar.as_view(), name="update_avatar"
    ),
    urls.path("rules/", forum_views.RulesPageView.as_view(), name="rules_view"),
    urls.path("register/", forum_views.CustomRegister.as_view(), name="register"),
    # path('autocomplete/', autocomplete, name='autocomplete')  # experimental
    # autocomplete
] + postview_patterns

# the following goes in the project top level urls.py
# from django_profile.views import CustomRegister
# path('users/accounts/register/', CustomRegister.as_view(), name='register'),

django_forum/templates/based.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        {% load static %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{{ siteName }}{% endblock title %}</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <meta name="description" content="">
         <meta name="keywords" content="">
         <meta name="author" content="">
        <link href="{% static 'django_forum/css/styles.css' %}" rel="stylesheet">
        <link href="{% static 'django_users/css/styles.css' %}" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Akaya+Kanadaka&family=Lobster+Two&family=Ubuntu:ital,wght@0,300;1,300&display=swap" rel="stylesheet">
        {% block extra_css %}
        {% endblock extra_css %}
        <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        type="application/javascript" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        {% block extra_js %}
        {% endblock extra_js %}
        {% block form_media %}
        {% endblock form_media %}
    </head>
    <body>
        <div class="container-fluid main-container">
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Things to do :</h4>
            <ul class="list-unstyled">
              {% if user.is_authenticated and '/email/' not in request.path %}
                <li><a href="{% url 'django_forum:post_list_view' %}" class="text-primary">Forum Posts</a></li>
                <li><a href="{% url 'django_forum:post_create_view' %}" class="text-dark">Create Post</a></li>
                <li><a href="{% url 'django_forum:profile_update_view' %}" class="text-success">Profile</a></li>
                <li><a href="{% url 'logout' %}" class="text-danger">Logout</a></li>
              {% else %}
                <li><a href="{% url 'login' %}" class="text-success">Login</a></li>
                <li><a href="{% url 'register' %}" class="text-primary">Register</a></li>
                <li><a href="{% url 'password_reset' %}" class="text-muted">Password reset</a></li>
                <li><a href="{% url 'resend_confirmation' %}" class="text-danger mt-3">Resend Confirmation Token</a>
              {% endif %}
            </ul>
          </div>
          {% block content %}
          {% endblock content %}
        </div> <!-- end .main-container -->
        {% block body_imports %}
        {% endblock body_imports %}
        {% block body_js %}
        {% endblock body_js %}
      </body>
</html>

django_forum/templates/links.html
<a href="profile/">Profile</a>
<a href="create_post/">Create Post</a>
<a href="posts/">List Posts</a>
<a href="rules/">Forum Rules</a>