django_forum/urls.py
"""
    _summary_
"""
from django import urls

from . import views as forum_views
from . import views_forum_post as forum_post_views

app_name = "django_forum"

postview_patterns = [
    urls.path("posts/", forum_post_views.PostList.as_view(), name="post_list_view"),
    urls.path(
        "post/<int:pk>/<slug:slug>/",
        forum_post_views.PostView.as_view(),
        name="post_view",
    ),
    urls.path(
        "create_post/", forum_post_views.PostCreate.as_view(), name="post_create_view"
    ),
    urls.path(
        "update_post/<int:pk>/<slug:slug>/",
        forum_post_views.PostUpdate.as_view(),
        name="post_update",
    ),
    urls.path(
        "delete_post/<int:pk>/<slug:slug>/",
        forum_post_views.PostDelete.as_view(),
        name="post_delete",
    ),
    urls.path(
        "report_post/<int:pk>/<slug:slug>/",
        forum_post_views.ReportPost.as_view(),
        name="post_report",
    ),
    urls.path(
        "create_comment/<int:pk>/<slug:slug>/",
        forum_post_views.CreateComment.as_view(),
        name="comment_create",
    ),
    urls.path(
        "delete_comment/<int:pk>/<slug:slug>/",
        forum_post_views.DeleteComment.as_view(),
        name="comment_delete",
    ),
    urls.path(
        "update_comment/<int:pk>/<slug:slug>/",
        forum_post_views.UpdateComment.as_view(),
        name="comment_update",
    ),
    urls.path(
        "report_comment/<int:pk>/<slug:slug>/",
        forum_post_views.ReportComment.as_view(),
        name="comment_report",
    ),
    urls.path("subscribe/", forum_post_views.subscribe, name="subscribe"),
]

urlpatterns = [
    urls.path(
        "profile/", forum_views.ForumProfile.as_view(), name="profile_update_view"
    ),
    urls.path(
        "update_avatar/", forum_views.UpdateAvatar.as_view(), name="update_avatar"
    ),
    urls.path("rules/", forum_views.RulesPageView.as_view(), name="rules_view"),
    urls.path("register/", forum_views.CustomRegister.as_view(), name="register"),
    # path('autocomplete/', autocomplete, name='autocomplete')  # experimental
    # autocomplete
] + postview_patterns

# the following goes in the project top level urls.py
# from django_profile.views import CustomRegister
# path('users/accounts/register/', CustomRegister.as_view(), name='register'),

django_forum/templates/django_forum/posts_and_comments/comment.html
{% load crispy_forms_tags %}
{% load cache %}
		<!-- COMMENTS -->
		<div class="ps-md-5 ps-lg-5 ps-sm-3 ps-2 col-12 col-lg-8 mx-auto">
		    <h3 class="tinfo mt-3 comment-headline">Comments...</h3>
		    {% load thumbnail %}
		        <div class="row mx-auto">
			        <div class="comments ps-4">
		    		{% for comment in comments %}
		    		{% cache 30 "comment" comment.slug comment.moderation_date request.user %}
		                <div class="flex-column mx-auto">
                                <div class="d-flex">
                                    <a href="/people/{{comment.author}}/">{% thumbnail comment.author.profile.avatar.image_file "40x40" crop="center" as im %}
                                        <img src="{{ im.url }}" height="{{ im.height }}" width="{{ im.width }}" class="rounded-circle me-1" value="image-{{ forloop.counter }}" title="{{comment.author}}"></img></a>
                                    {% endthumbnail %}
    		                	    <a class="comment-link col-1" href="{{request.path}}#{{comment.slug}}" id="{{ comment.slug }}"><h2 class="text-warning me-1">#</h2></a>
		                				{% if not comment.moderation_date %}
    			                	<div id="comment-text-{{ forloop.counter }}" class="comment-text">
    			                        {{ comment.text|linebreaks|urlize|safe }}
    	                            </div>
                                </div>
                            {% else %}
                                <div id="mod-msg">This comment has been reported and is awaiting moderation.</div>
                            {% endif%}
                            {% if comment.author == request.user %}
                            <div id="comment-form-buttons-{{ forloop.counter }}" class="comment-form-buttons">
                            	<form method="post" action="{% url 'django_forum:comment_update' comment.id comment.slug %}" id="comment-update-form-{{ forloop.counter }}" class="comment-update-form">
                            		{% csrf_token %}
                            		<div class="row">
                            			<div class="col-auto">
                                    		<textarea id="comment-textarea-{{ forloop.counter }}" form="comment-update-form-{{ forloop.counter }}" wrap="hard" rows="6" cols="60" class="comment-textarea" name="text"></textarea>
                                    	</div>
                                    </div>
                                    <div class="row">
                                    	<div class="col-auto ms-auto">
                                    	    <a id="comment-save-{{ forloop.counter }}" class="comment-save tinfo me-2" href="#">Save Comment</a>
                                    	    <a id="cancel-{{ forloop.counter }}" class="comment-cancel tinfo" href="#">Cancel Update</a>
                                        </div>
                                    </div>
                              	</form>
                            </div>
                            {% elif not comment.moderation_date %}
                            <div class="ms-auto">
			                    <form method="post" action="{% url 'django_forum:comment_report' comment.id comment.slug %}" id="form-report-comment">
			                    	{% csrf_token %}
			                    	<div class="tinfo">
			                        	<a class="report-comment text-warning" href="#">Report Comment for Moderation</a>
			                    	</div>
			                    </form>
			                </div>
                            {% endif %}
                        </div>
                        <div class="row justify-content-end mb-3">
			                {% if comment.moderation_date is None and comment.author == request.user %}
		                    <div id="comment-modify-btns-{{ forloop.counter }}" class="col-auto">
			                	<a id="delete-comment-{{ forloop.counter }}" href="#" class="tinfo col-auto me-3" data-bs-toggle="modal" data-bs-target="#comment-modal" data-bs-comment-id="{{comment.id}}" data-bs-comment-slug="{{comment.slug}}">Delete Comment</a>
			                	<a id="edit-comment-{{ forloop.counter }}" class="comment-edit tinfo col-auto" href="#">Edit Comment</a>
				            </div>
				            {% endif %}
				        </div>
	                    <div class="row justify-content-end">
	                        <span class="col-auto tinfo fs-6 font-weight-normal">
	                                {{ comment.created_at }}
	                        </span>
	                    </div>
	                {% endcache %}
            		{% endfor %}
			        </div>
        	    </div>
            {% if post.commenting_locked == False and post.moderation_date is None %}
            <div class="row">
	            <div class="card-body mx-auto">
	                <form id="comment-form" method="post" action="{% url 'django_forum:comment_create' post.id post.slug %}" class="comment-form">
	                <input type="hidden" name="author" value="{{ user }}">
	                  {% crispy comment_form %}
	                  {% csrf_token %}
	                </form>
	            </div>
            </div>
            {% else %}
            <div class="row tinfo mb-4">
            	<div class="col-auto">
	            	<div id="comment-locked" class="comment-headline">
	            		Commenting has been locked for this post.
	            	</div>
            		Contact an admin if you disagree...
            	</div>
            </div>
            {% endif %}
			<!-- Confirm Delete Comment Modal -->
            <div class="modal fade" id="comment-modal" tabindex="-1" aria-labelledby="comment-modal-label" aria-hidden="true">
				<div class="modal-dialog">
				  <div class="modal-content">
					<div class="modal-header">
					  <h5 class="modal-title" id="comment-modal-label">Confirm Comment Deletion</h5>
					  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
					  <h4>Warning!</h4><p>You are about to delete this Comment.  This action cannot be undone!  Proceed carefully...</p>
					</div>
					<div class="modal-footer">
					  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					  <form method="post" id="delete-form" data-action="{% url 'django_forum:comment_delete' 0 'slug' %}">
						{% csrf_token %}
						<button type="submit" class="btn btn-primary">Delete Comment</button>
					  </form>
					</div>
				  </div>
				</div>
			  </div>
        </div>

django_forum/templates/django_forum/posts_and_comments/forum_post_create_form.html
{% extends BASE_HTML %}
{% block title %}{{ siteName }} - Create a Post!{% endblock title %}
{% load static %}
{% load pipeline %}
{% block form_media %}
<script src="{% static 'tinymce/tinymce.min.js' %}" type="application/javascript" referrerpolicy="origin"></script>
<script src="{% static 'tinymce/jquery.tinymce.min.js' %}" type="application/javascript" referrerpolicy="origin"></script>
{% endblock form_media %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
	{% block content %}
        <div class="container"> 
			<div class="row vh-100">
					{% csrf_token %}
				    {% crispy form %}
			</div>
		</div>
	{% endblock %}
{% endif %}
{% block body_js %}
{% endblock body_js %}
{% block body_imports %}
    {% javascript 'forum_post_create' %}
{% endblock body_imports %}

django_forum/templates/django_forum/posts_and_comments/forum_post_detail.html
{% extends BASE_HTML %}
{% load static %}
{% load pipeline %}
{% block title %}{{ siteName }} - Post{% endblock title %}
{% block extra_css %}
{% endblock extra_css %}
{% block form_media %}
<script src="{% static 'tinymce/tinymce.min.js' %}" type="application/javascript" referrerpolicy="origin"></script>
<script src="{% static 'tinymce/jquery.tinymce.min.js' %}" type="application/javascript" referrerpolicy="origin"></script>
{% endblock form_media %}
{% block content %}
<div id="thepost" class="container" class="post-and-comments-container">
	<div class="row h-75 my-auto">
		{% include './post.html' %}
		{% include './comment.html' %}
	</div>
</div>
{% endblock %}
{% block body_js %}
	{% javascript 'forum_post_detail' %}
{% endblock body_js %}

django_forum/templates/django_forum/posts_and_comments/forum_post_list.html
{% extends BASE_HTML %}
{% load crispy_forms_tags %}
{% block title %}{{ siteName }} - Forum Posts{% endblock title %}
{% block content %}
    {% if not page_obj.object_list.exists and is_a_search is False %}
        <div class="row">
            <div class="col-auto mx-auto mt-5">
                <p><h3>There are currently no posts in the forum.  Why not <a href="{% url 'django_forum:post_create_view' %}" class="tinfo">add</a> one...?</h3></p>
            </div>
        </div>
    {% else %}
        <div class="container-fluid main-container-post">
           <div class="row justify-content-center tinfo">
                <h1 class="post-headline col-auto">Forum Posts...</h1>
            </div>
            <div class="row justify-content-center tinfo">
                <p class="col-auto">Search the posts for content, author or category.</p>
            </div>
            <div class="row justify-content-center">
                <form method="get" class="search-form">
                  {% crispy form %}
                </form>
            </div>
            <div class="row justify-content-center">
                {% if is_a_search is True %}
                    {% if search > 0 %}
                        <h5 class="comment-headline tinfo">Search Results</h5>
                    {% else %}
                        <h5 class="comment-sm-headline tinfo">There are no search results</h5>
                        <h5 class="comment-sm-headline tinfo">so here are the Posts...</h5>
                    {% endif %}
                {% endif %}
            </div>
            {% include './post_list.html' %}
            {% if is_a_search is True and search > 0 %}
            <div class="row justify-content-center">
                <a href='{% url "django_forum:post_list_view" %}' class="btn btn-primary mb-4 col-auto">Clear Search Results</a>
            </div>
            {% endif %}
        </div>
    {% endif %} 
{% endblock %}

django_forum/templates/django_forum/posts_and_comments/oldpost.html
            <form method="post" action="{% url 'django_forum:post_update' post.pk post.slug %}">
                <div class="row align-items-end tinfo post-headline mb-2">
                    <div id="title-div" {% if title_errors %}class="col-auto border border-danger"{% else %}class="col-auto"{% endif %}>
                        <h1><span id="post_title">{{ post.title|safe }}</span></h1>
                        <div class="errors">{{ title_errors|linebreaks }}</div>
                    </div>
                    <div class="post-edit-div">
                        <input id="title_input" name="title">
                    </div>
                    <div class="col-auto">
                        <h1><span class="text-dark ps-2">by</span></h1>
                    </div>
                    <div class="col-auto">
                        <h3>{{ post.author.profile.display_name }}</h3>
                    </div>
                    <div class="col-auto">
                        <h3><span class="text-dark ps-3">on</span></h3>
                    </div>
                    <div class="col-auto">
                        <h4>{{ post.created_at }}</h4>
                    </div>
                </div>
                <div class="tinfo row justify-content-start mb-2">
                    <div class="col-auto"><input type='checkbox' id='subscribed_cb' {% if subscribed %}checked{% endif %}><label for="subscribed_cb" class="ps-2">{% if subscribed %}Subscribed{% else %}Subscribe{% endif %} to this thread</label></div>
                </div>
                <div class="row ms-auto mb-2">
                    {% if not post.moderation_date %}
                    <div id="textarea" class="col-auto" required="">{{ post.text|safe }}</div>
                    <div id="text-errors" {% if text_errors %}class="errors ms-auto border border-danger"{% else %}class="col-auto"{% endif %}>{{ text_errors }}</div>
                    {% else %}
                    <div>This post has been reported and is awaiting moderation.  Comments are locked until the post has been validated.</div>
                    {% endif %}
                    {% if post.author == user %}
                        <div class="ms-auto">
                                {% csrf_token %}
                                <div class="post-edit-div">
                                    <input type="textarea" name="text" class="update-form-text"></input>
                                    <input type="hidden" name="type" value="update">
                                    <div class="mt-3">
                                        <button id="editor-cancel-btn" type="button" class="ms-auto col-auto btn btn-secondary me-2">Cancel</button>
                                        <button id="editor-submit-btn" type="submit" class="me-auto col-auto btn btn-primary">
                                        Save Post</button>
                                    </div>
                                </div>
                        </div>
                    {% else %}
                        {% if not post.moderation_date and post.author != user %}
                        <div class="ms-auto">
                            <form method="post" action="{% url 'django_forum:post_report' %}" id="form-report-post">
                                {% csrf_token %}
                                <input id="post-id" type="hidden" name="post-id" value="{{ post.id }}">
                                <input id="post-slug" type="hidden" name="post-slug" value="{{ post.slug }}">
                                <div class="tinfo">
                                    <a class="report-post text-warning" href="#">Report Post for Moderation</a>
                                </div>
                        </div>
                        {% endif %}
                    {% endif %}
                </div>
                </form>

django_forum/templates/django_forum/posts_and_comments/post.html
		{% load thumbnail %}
		{% load static %}
		<div id='thepost' class="col-12 col-sm-11 col-md-12 col-lg-9 mx-auto my-auto">
			<div class='ps-4'>
				<form method="post" action="{% url 'django_forum:post_update' post.pk post.slug %}">
					<div class="row align-items-end tinfo post-headline mb-2">
						<div id="title-div" {% if title_errors %}class="col-auto border border-danger"{% else %}class="col-auto"{% endif %}>
						    {% if not post.moderation_date %}
						    	<span id="post-title">{{ post.title|safe }}</span>
						    	<div class="errors">{{ title_errors|linebreaks }}</div>
						    {% else %}
						    	<span id="post-title"><h4>awaiting moderation</h4></span>
						    {% endif %}
					    </div>
					    <div class="post-edit-div">
					    	<input id="title-input" name="title">
					    </div>
					    <div class="col-auto">
					    	<h1><span class="text-dark ps-2">by</span></h1>
					    </div>
					    <div class="col-auto">
					    	<h3>{{ post.author.profile.display_name }}</h3>
					    </div>
					    <div class="col-auto">
					    	<h3><span class="text-dark ps-3">on</span></h3>
					    </div>
					    <div class="col-auto">
					    	<h4>{{ post.created_at }}</h4>
					    </div>
					</div>
					<div class="tinfo row justify-content-start mb-2">
					    <div class="col-auto"><input type='checkbox' id='subscribed_cb' {% if subscribed %}checked{% endif %}><label for="subscribed_cb" class="ps-2">{% if subscribed %}Subscribed{% else %}Subscribe{% endif %} to this thread</label></div>
					</div>
					<div class="row ms-auto mb-2">
						{% if not post.moderation_date %}
					    <div id="textarea" class="col-auto" required="">{{ post.text|safe }}</div>
					    <div id="text-errors" {% if text_errors %}class="errors ms-auto border border-danger"{% else %}class="col-auto"{% endif %}>{{ text_errors }}</div>
					    {% else %}
					    <div id="mod-msg">This post has been reported and is awaiting moderation.  Comments are locked until the post has been validated.</div>
					    {% endif %}
					</div>
			    </form>
			</div>
		    {% if post.author == user %}
			    <div class="ms-auto">
	    		    	{% csrf_token %}
	    		    	<div class="post-edit-div">
	    		    		<input type="textarea" name="text" class="update-form-text"></input>
			    		    <input type="hidden" name="type" value="update">
			    		    <div class="mt-3">
			                    <button id="editor-cancel-btn" type="button" class="ms-auto col-auto btn btn-secondary me-2">Cancel</button>
			                    <button id="editor-submit-btn" type="submit" class="me-auto col-auto btn btn-primary">
			                    Save Post</button>
			                </div>
		                </div>
	            </div>
            {% else %}
                {% if not post.moderation_date and post.author != user %}
                <div class="ms-auto">
                    <form method="post" action="{% url 'django_forum:post_report' post.id post.slug %}" id="form-report-post">
                    	{% csrf_token %}
                    	<div class="tinfo">
                            <a class="report-post text-warning" href="#">Report Post for Moderation</a>
                    	</div>
	    			</form>
                </div>
                {% endif %}
	        {% endif %}
		    <div class="row justify-content-end mb-3">
	    		{% if not post.moderation_date and post.author == user %}
	    		    <div id="modify-post-btns">
	    		    	<div class="d-flex justify-content-end">
			    			<button id="delete-btn" type="button" class="btn btn-secondary col-auto me-2" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">Delete Post</button>
		    		    	<button id="editor-btn" class="col-auto btn btn-primary">Edit Post</button><!--edit handled by ajax in forum app-->
	    		    	</div>
	    		    </div>
	    		{% endif %}
		    </div>
		    <!-- Confirm Delete Post Modal -->
		    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
		      <div class="modal-dialog">
		        <div class="modal-content">
		          <div class="modal-header">
		            <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Post Deletion</h5>
		            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		          </div>
		          <div class="modal-body">
		            <h4>Warning!</h4><p>You are about to delete this post.  This action cannot be undone!  Proceed carefully...</p>
		          </div>
		          <div class="modal-footer">
		            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
		            <form action='{% url "django_forum:post_delete" post.id post.slug %}' method="post">
		            {% csrf_token %}
		            <input type="hidden" name="type" value="post">
		            <button type="submit" class="btn btn-primary">Delete Post</button>
		            </form>
		          </div>
		        </div>
		      </div>
		    </div>
		</div>

django_forum/templates/django_forum/posts_and_comments/post_list.html
{% load thumbnail %}
{% load crispy_forms_tags %}
<div class="mb-3" class="post-list">
                <table>
                    <tbody id="post-table" class="tinfo">
                    <tr class="sub-headline-text">
                        <th></th>
                        <th>Title (try clicking one)</th>
                        <th>Post Leader</th>
                        <th class="text-center"># Comments</th>
                        <th>Date</th>
                    </tr>
                        {% for post in page_obj.object_list %}
                            {% if not post.moderation_date %}
                            <tr >
                               <td>
                                {% thumbnail post.author.profile.avatar.image_file "50x50" crop="center" as im %}
                                    <img src="{{ im.url }}" height="{{ im.height }}" width="{{ im.width }}" class="rounded-circle" id="image-{{ post.author.profile.display_name }}_avatar-image" title="{{ post.author.profile.display_name }}" alt="{{ post.author.profile.display_name }}"/>
                                {% endthumbnail %}
                                </td>
                                <td>
                                    <a href="{{ post.get_absolute_url|safe }}#thepost" class="tinfo">{{ post.title }}</a>
                                </td>
                                <td>
                                    {{ post.text|striptags|safe|slice:":40" }}...
                                </td>
                                <td class="text-center">
                                    {{ post.comments.count }}
                                </td>
                                <td>
                                    {{ post.created_at|date }}
                                </td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row">
                {% if request.path == '/forum/posts/' %}
                    <div class="col-3 mx-auto fixed-bottom mb-3">
                {% else %}
                    <div class="col-3 mx-auto">
                {% endif %}
                    <div class="row pagination">
                        <span class="d-flex step-links justify-content-around flex-fill">
                            {% if page_obj.has_previous %}
                                <a class="tinfo" href="?page=1">&laquo; first</a>
                                <a class="tinfo" href="?page={{ page_obj.previous_page_number }}">...previous</a>
                            {% endif %}

                            <span class="current col-auto tinfo">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a class="tinfo" href="?page={{ page_obj.next_page_number }}">next...</a>
                                <a class="tinfo" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>