django_forum/urls.py
"""
    _summary_
"""
from django import urls

from . import views as forum_views
from . import views_forum_post as forum_post_views

app_name = "django_forum"

postview_patterns = [
    urls.path("posts/", forum_post_views.PostList.as_view(), name="post_list_view"),
    urls.path(
        "post/<int:pk>/<slug:slug>/",
        forum_post_views.PostView.as_view(),
        name="post_view",
    ),
    urls.path(
        "create_post/", forum_post_views.PostCreate.as_view(), name="post_create_view"
    ),
    urls.path(
        "update_post/<int:pk>/<slug:slug>/",
        forum_post_views.PostUpdate.as_view(),
        name="post_update",
    ),
    urls.path(
        "delete_post/<int:pk>/<slug:slug>/",
        forum_post_views.PostDelete.as_view(),
        name="post_delete",
    ),
    urls.path(
        "report_post/<int:pk>/<slug:slug>/",
        forum_post_views.ReportPost.as_view(),
        name="post_report",
    ),
    urls.path(
        "create_comment/<int:pk>/<slug:slug>/",
        forum_post_views.CreateComment.as_view(),
        name="comment_create",
    ),
    urls.path(
        "delete_comment/<int:pk>/<slug:slug>/",
        forum_post_views.DeleteComment.as_view(),
        name="comment_delete",
    ),
    urls.path(
        "update_comment/<int:pk>/<slug:slug>/",
        forum_post_views.UpdateComment.as_view(),
        name="comment_update",
    ),
    urls.path(
        "report_comment/<int:pk>/<slug:slug>/",
        forum_post_views.ReportComment.as_view(),
        name="comment_report",
    ),
    urls.path("subscribe/", forum_post_views.subscribe, name="subscribe"),
]

urlpatterns = [
    urls.path(
        "profile/", forum_views.ForumProfile.as_view(), name="profile_update_view"
    ),
    urls.path(
        "update_avatar/", forum_views.UpdateAvatar.as_view(), name="update_avatar"
    ),
    urls.path("rules/", forum_views.RulesPageView.as_view(), name="rules_view"),
    urls.path("register/", forum_views.CustomRegister.as_view(), name="register"),
    # path('autocomplete/', autocomplete, name='autocomplete')  # experimental
    # autocomplete
] + postview_patterns

# the following goes in the project top level urls.py
# from django_profile.views import CustomRegister
# path('users/accounts/register/', CustomRegister.as_view(), name='register'),

django_forum/templates/django_forum/profile/forum_profile_update_form.html
{% extends BASE_HTML %}
{% block title %}{{ siteName }} - Update Profile{% endblock title %}
{% load static %}
{% load pipeline %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
    {% load thumbnail %}
    {% block extra_css %}
    {% endblock extra_css %}
    {% block content %}
        <div class="row my-auto ms-3">
            <div class="col-auto">
                <form method="post" class="avatarform mb-3" id="avatarform" action="{% url 'django_forum:update_avatar' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="type" value="update-avatar">
                    {% thumbnail avatar.image_file "80x80" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="btTxt img-thumbnail" role="button" id="avatarImage" title="Click me to change avatar!" />
                    {% endthumbnail %}
                    <input id="avatarUpload" class="d-none" type="file" name="avatar">
                </form>
            </div>
            <div class="col-11 col-sm-9 col-md-7 col-lg-5 mb-3">
                <form method="post" action="{% url 'django_forum:profile_update_view' %}" class="col-auto" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="type" value="update-profile">
                    <fieldset legend="profile">
                    {% crispy user_form %}
                    {% crispy form %}
                    </fieldset>
                    <div class="row justify-content-between">
                        <a href="{% url 'django_forum:post_list_view' %}" class="col-auto tinfo mb-3">Return to Forum</a>
                        <button type="submit" class="btn btn-primary col-auto mb-3">Update Profile</button>
                    </div>
                </form>
            </div>
            {% if page_obj.object_list.exists %}
            <div class="col-12 col-lg-5 mx-auto">
                <h3 class="text-center headline-text">My Posts</h3>
                {% include '../posts_and_comments/post_list.html' %}
            </div>
            {% endif %}
        </div>
    {% endblock content %}
    {% block body_js %}
        {% javascript 'forum_profile_update' %}
    {% endblock body_js %}
{% endif %}